source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks! 

target 'ExportAPISample' do
  pod 'BanubaVideoEditorEffectsSDK', '1.0.18.2'
  pod 'VideoEditor', '1.0.18.2'
  pod 'BanubaUtilities', '1.0.18.2'
  pod 'BanubaLicenseServicingSDK', '1.0.18.2'
  pod 'BanubaSDKServicing', '1.0.18.2'
  pod 'BNBLicenseUtils', '1.0.18.1'

  pod 'BSImagePicker'
  
end
