source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks! 

target 'ExportAPISample' do
  pod 'VEEffectsSDK', '1.22.0'
  pod 'VideoEditor', '1.22.0'
  pod 'BanubaUtilities', '1.22.0'
  pod 'BanubaLicenseServicingSDK', '1.22.0'
  pod 'BanubaSDKServicing', '1.22.0'
  pod 'BNBLicenseUtils', '1.22.0'
  pod 'VEExportSDK', '1.22.0'

  pod 'BSImagePicker'
  
end
